if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_SYSTEM_NAME "Windows")
endif()

set(CMAKE_SYSTEM_PROCESSOR "x86_64")

set(CPACK_SYSTEM_NAME "win64")
set(GMOD_LIBTIER0_DIR "bin/win64")
set(GMOD_LUASHARED_DIR "bin/win64")
set(GMOD_MODULE_ARCH "win64")

find_program(CMAKE_C_COMPILER NAMES "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc-posix" "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc" REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++-posix" "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++" REQUIRED)
