if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_SYSTEM_NAME "Windows")
endif()

set(CMAKE_SYSTEM_PROCESSOR "i686")

set(CPACK_SYSTEM_NAME "win32")
set(GMOD_LIBTIER0_DIR "bin")
set(GMOD_LUASHARED_DIR "garrysmod/bin")
set(GMOD_MODULE_ARCH "win32")

find_program(CMAKE_C_COMPILER NAMES "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc-posix" "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc" REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++-posix" "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++" REQUIRED)
